name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        # if you want cross platform support 
        os: [ ubuntu-latest ]
        experimental: [false]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

    - name: Restore Rust Cache
      uses: Swatinem/rust-cache@v1

    - name: Run cargo test 
      uses: actions-rs/cargo@v1
      with:
        command: test
    
    - name: Setup trunk
      uses: jetli/trunk-action@v0.1.0
      with:
          version: "latest"

    - name: Debug Build
      run: trunk -v build 

    - name: Release Build
      run: trunk -v build --release 
